-- Code generated by protoc-gen-emmylua. DO NOT EDIT.
-- versions:
-- 	protoc-gen-go v1.0
-- 	protoc        v3.21.8
-- 	time          2023-08-05 22:39:38
-- source: test.proto

local proto = {}

---@class ETest
---@field public E_1 integer|string @0
---@field public E_2 integer|string @1

---@type ETest
proto.ETest = {
	E_1 = 0,
	E_2 = 1,
}

---@type ETest
proto.ETestStr = {
	E_1 = "E_1",
	E_2 = "E_2",
}

---@class Test
---@field A integer
---@field B string
---@field C float
---@field D ETest
---@field E string[]
---@field F table<integer,string>
---@field G Test_Unit

---@class Test_Unit
---@field A integer

return proto
