-- Code generated by protoc-gen-emmylua. DO NOT EDIT.
-- versions:
-- 	protoc-gen-go v1.0
-- 	protoc        v3.21.8
-- 	time          2023-08-07 16:16:21
-- source: test.proto

local proto = {}

---@class ETest @test ETest
---@field public E_1 integer|string @0 comment E_1
---@field public E_2 integer|string @1 

---@type ETest
proto.ETest = {
	E_1 = 0,
	E_2 = 1,
}

---@type ETest
proto.ETestStr = {
	E_1 = "E_1",
	E_2 = "E_2",
}

---@class Test @test message
---@field A integer @comment A
---@field B string 
---@field C float 
---@field D ETest 
---@field E string[] 
---@field F table<integer,string> 
---@field G Test_Unit 

proto.Test = "Test"
---@class Test_Unit @
---@field A integer @comment A

proto.Test_Unit = "Test_Unit"
return proto
